export const ERROR_EXCEPTION = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_ALREADY_ENROLLED: 'STUDENT_ALREADY_ENROLLED',
  CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
}